---
  hosts: win
  gather_facts: false
  tasks:
  - name: Ejecutar comando en PowerShell
    win_shell: Get-Service -Name service | Stop-Service

  - name: Ejecutar comando en cmd
    win_shell: mkdir C:\temp
    args:
    executable: cmd.exe

  - name: Ejecutar multiples comandos en shell
    win_shell: |
      New-Item -Path C:\temp -ItemType Directory
      Remove-Item -Path C:\temp -Force -Recurse
      $path_info = Get-Item -Path C:\temp
      $path_info.FullName

  - name: Ejecutar un comando de cmd
    win_command: cmd.exe /c mkdir C:\temp

  - name: Ejecutar un vbs script
    win_command: cscript.exe script.vbs